### ISSUE TITLE
password

### ISSUE THREAD

**Issue by jilner** [ceshine/fast-neural-style#3]
when I open the code with jupyter notebook  ,  it needs password?

**Comment by ceshine** [comment]
Please replace the 'password' field in `jupyter_notebook_config.json` with your own or just remove it. 

Somehow I forgot to remove that when committing. It's just for saving me the trouble of copying tokens from the command line.

**Comment by ceshine** [comment]
The `jupyter_notebook_config.json` file has been removed from the master. Should avoid this kind of confusions in the future. Thanks for reporting the issue!
